name: Deploy to GitHub Pages
run-name: ${{ github.actor }} is deploying babystep.io 🚀

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Deploy-Website:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Jekyll build
        run: |
          set -x
          bundle exec jekyll build --trace

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: "_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
